### ISSUE TITLE
Dashboard widget

### ISSUE THREAD

**Issue by AaronHolbrook** [blazersix/satispress#27]
I like to check in on my satispress install to ensure / see what plugins have been updated, would be useful to have a dashboard plugin to summarize any new changes/etc that have happened, or to inform me of any issues (i.e. a plugin failed to update and requires my attention).

**Comment by GaryJones** [comment]
Would a general purpose logging plugin not be better suited for this?

**Comment by AaronHolbrook** [comment]
I think this is pretty unique to what satispress does and what it's doing could be usefully reported (i.e. updated plugin xyz to version 1.3.2 on tuesday).

**Comment by GaryJones** [comment]
I disagree, for exactly the reasons you've specified. I've not tried it, but something like https://wordpress.org/plugins/aryo-activity-log/ (and there are others out there) keep track of Plugin installs, updates etc. Combine that with automatic minor and major updates, and it will run smoothly and keep track of everything too. No need for  SatisPress to bundle this as well, since we don't interact with plugin updates specifically.

**Comment by AaronHolbrook** [comment]
Fair enough, I just thought it would be nice to have something specifically set up for tracking new releases, and although satispress doesn't handle the updating, it does track/manage the versions.

**Comment by bradyvercher** [comment]
I'm going to go ahead and close this out. We can consider it later if it gets any more interest.

In the meantime, running `composer outdated` should show any packages that have updates available.
