### ISSUE TITLE
Consider allowing some packages to be set as public?

### ISSUE THREAD

**Issue by GaryJones** [blazersix/satispress#53]
Not seen it asked for, but could some packages be exposed as public i.e. bypass Basic Auth, while others stay protected? Might need `packages.json` to effectively have a _public_ view and an _authenticated_ view. 

Even if it's not built-in, having example code snippet in the /docs for how to amend the visibility and access of specific packages (or even specific releases of packages) would be very cool indeed.

**Comment by bradyvercher** [comment]
I don't see why not, but authentication happens pretty early, so whether or not it's enabled for a particular resource would probably depend on the request parameters.

Otherwise, with another `current_user_can()` check or two in the routes for individual packages and releases, it should be possible to create pretty granular rules using the `map_meta_cap` filter.

I'm also guessing having a separate URL for the public view and authenticated view might be necessary to work around potential caching issues and knowing when to send the `WWW-Authenticate` header to prompt clients for credentials.

**Comment by bradyvercher** [comment]
After thinking this over a bit more, it would probably require a little more than a snippet, so this is probably good territory for an add-on. This is a pretty basic approach, though:

```php
<?php
/**
 * Disable the authentication challenge.
 */
add_filter( 'satispress_authentication_servers', function( $servers ) {
	unset( $servers[100] );
	return $servers;
} );

/**
 * Filter which plugins should be publicly accessible.
 */
add_filter( 'satispress_plugins', function( $plugins ) {
	if ( is_user_logged_in() ) {
		return $plugins;
	}

	return [
		'akismet/akismet.php',
	];
} );

/**
 * Filter which themes should be publicly accessible.
 */
add_filter( 'satispress_themes', function( $themes ) {
	if ( is_user_logged_in() ) {
		return $themes;
	}

	return [];
} );

/**
 * Grant the ability to download and view packages to all users.
 *
 * This is pretty rudimentary and relies on the Whitelist repository to not be
 * replaced throughout SatisPress. Ideally, the capabilities would be denied
 * if the package should not be publicly avaialble by checking the $args argument.
 */
add_filter( 'user_has_cap', function( $allcaps, $caps, $args, $user ) {
	if ( is_user_logged_in() ) {
		return $allcaps;
	}

	$allcaps[ Capabilities::DOWNLOAD_PACKAGES ] = true;
	$allcaps[ Capabilities::VIEW_PACKAGES ]     = true;

	// @todo Set capabilities to false if the package shouldn't be publicly available.

	return $allcaps;
}, 10, 4);
```
